// flow-typed signature: 2d9deca6bd52577916e1d3c4d4d28fff
// flow-typed version: <<STUB>>/deepmerge_v^1.3.2/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'deepmerge'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'deepmerge' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'deepmerge/index' {
  declare module.exports: $Exports<'deepmerge'>;
}
declare module 'deepmerge/index.js' {
  declare module.exports: $Exports<'deepmerge'>;
}
