version: 2
jobs:
  test-node-6:
    working_directory: ~/app
    docker:
      - image: circleci/node:6
    steps:
      - checkout
      - run:
          name: which-node
          command: which node
      - run:
          name: node-version
          command: node -v
      - restore_cache:
          key: yarn-cache-node6-{{ arch }}-{{ checksum "yarn.lock" }}
      - run:
          name: yarn
          command: npm run yarn
      - save_cache:
          key: yarn-cache-node6-{{ arch }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run:
          name: lint
          command: npm run lint
      - run:
          name: flow-ci
          command: npm run flow-ci
      - run:
          name: test-jest
          command: npm run test-jest -- --runInBand

  test-node-8:
    working_directory: ~/app
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run:
          name: which-node
          command: which node
      - run:
          name: node-version
          command: node -v
      - restore_cache:
          key: yarn-cache-node8-{{ arch }}-{{ checksum "yarn.lock" }}
      - run:
          name: yarn
          command: npm run yarn
      - save_cache:
          key: yarn-cache-node8-{{ arch }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run:
          name: lint
          command: npm run lint
      - run:
          name: flow-ci
          command: npm run flow-ci
      - run:
          name: test-jest
          command: npm run test-jest -- --runInBand

  test-node-10:
    working_directory: ~/app
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: which-node
          command: which node
      - run:
          name: node-version
          command: node -v
      - restore_cache:
          key: yarn-cache-node10-{{ arch }}-{{ checksum "yarn.lock" }}
      - run:
          name: yarn
          command: npm run yarn
      - save_cache:
          key: yarn-cache-node10-{{ arch }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run:
          name: lint
          command: npm run lint
      - run:
          name: flow-ci
          command: npm run flow-ci
      - run:
          name: test-jest
          command: npm run test-jest -- --runInBand

  bump-version:
    working_directory: ~/app
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run:
          name: which-node
          command: which node
      - run:
          name: node-version
          command: node -v
      - run:
          name: bump-version
          command: bin/bump_version.sh

workflows:
  version: 2
  run-tests-and-release:
    jobs:
      - test-node-6
      - test-node-8
      - test-node-10
      - bump-version:
          filters:
            branches:
              only: master
          requires:
            - test-node-6
            - test-node-8
            - test-node-10
